# Generated by Django 4.1.2 on 2022-10-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('i_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.ingredient')),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('i_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.ingredient')),
                ('s_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
