# Generated by Django 4.1.2 on 2022-10-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_recipeingredient_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
