# Generated by Django 4.1.2 on 2022-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
