# Generated by Django 4.1.2 on 2022-10-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='ingredient-images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe-images/'),
        ),
    ]
