# Generated by Django 4.1.2 on 2022-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_ingredient_image_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
