# Generated by Django 4.1.2 on 2022-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_ingredient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
